model:
  vocab_size: 25
  d_model: 512
  n_heads: 8
  n_layers: 12
  max_seq_length: 1024
  hierarchical_levels: 3
  physics_features: 64

training:
  batch_size: 32
  learning_rate: 1e-4
  weight_decay: 1e-5
  max_epochs: 100
  warmup_steps: 1000
  gradient_clip: 1.0
  
  # Novel training objectives
  loss_weights:
    function_prediction: 1.0
    structure_prediction: 0.5
    stability_prediction: 0.3
    physics_consistency: 0.2
    evolutionary_similarity: 0.1

physics:
  enable_distance_bias: true
  enable_interaction_matrix: true
  enable_secondary_structure_bias: true
  physics_regularization: 0.01

data:
  datasets:
    - "UniProt/Swiss-Prot"  # High quality protein sequences
    - "PDB"                 # Structural data
    - "GO"                  # Function annotations
    
  preprocessing:
    max_sequence_length: 1024
    min_sequence_length: 50
    remove_ambiguous: true